### PR TITLE
Using Genius instead of last.fm

### PR DESCRIPTION
**Pull request by sldless**
sorry if my description didn't make sense but basically I made it get info instead of genius instead of last.fm

### CODE REVIEW

**Comment by sldless** [comment]
interesting, I don't know what happened .

**Comment by metalandcoffee** [comment]
Hey @sldless! Would have been cool to see your Genius implementation! That sounds cool.

**Comment by sldless** [comment]
Hey @metalandcoffee!

Should I include last.fm? because am only using genius

**Comment by metalandcoffee** [comment]
You don't have to include it if you don't want to! This is your implementation of it. Can be totally different from mine.

**Pull request merged**
